// Config plugin: wire up release signing + CI version overrides in the
// generated android/app/build.gradle. The android/ directory is NOT committed
// (continuous native generation — `expo prebuild` regenerates it), so these
// edits must be injected at prebuild time; see docs/releasing.md.
//
// - The release build type gets its own signing config, read from the
//   ANDROID_KEYSTORE_PATH / ANDROID_KEYSTORE_PASSWORD / ANDROID_KEY_ALIAS /
//   ANDROID_KEY_PASSWORD environment variables at *Gradle build* time (the
//   release workflow decodes the ANDROID_KEYSTORE secret into a file and sets
//   these). When unset — local dev, or CI before the secrets exist — it falls
//   back to the debug keystore so the build still produces installable output.
// - versionCode / versionName come from NOMAD_VERSION_CODE / NOMAD_VERSION_NAME
//   (the workflow derives them from the release tag), defaulting to app.json's
//   values offline.
const { withAppBuildGradle } = require('@expo/config-plugins')

const RELEASE_SIGNING_CONFIG = `
        release {
            if (System.getenv('ANDROID_KEYSTORE_PATH')) {
                storeFile file(System.getenv('ANDROID_KEYSTORE_PATH'))
                storePassword System.getenv('ANDROID_KEYSTORE_PASSWORD')
                keyAlias System.getenv('ANDROID_KEY_ALIAS')
                keyPassword System.getenv('ANDROID_KEY_PASSWORD')
            } else {
                // No release keystore in the environment — sign with the debug
                // keystore so the build still works.
                storeFile file('debug.keystore')
                storePassword 'android'
                keyAlias 'androiddebugkey'
                keyPassword 'android'
            }
        }`

function replaceOrThrow (contents, pattern, replacement, what) {
  if (!pattern.test(contents)) {
    throw new Error(
      `[withReleaseSigning] could not find ${what} in android/app/build.gradle — ` +
        'the template generated by expo prebuild has changed; update plugins/withReleaseSigning.js'
    )
  }
  return contents.replace(pattern, replacement)
}

module.exports = function withReleaseSigning (config) {
  return withAppBuildGradle(config, (cfg) => {
    let s = cfg.modResults.contents

    if (!s.includes('signingConfigs.release')) {
      // Add a release entry to signingConfigs, right after the debug one
      s = replaceOrThrow(
        s,
        /(signingConfigs\s*\{\s*debug\s*\{[^}]*\})/,
        `$1${RELEASE_SIGNING_CONFIG}`,
        'the signingConfigs.debug block'
      )
      // Point the release build type at it (the template signs release builds
      // with the debug keystore, behind a "Caution!" comment)
      s = replaceOrThrow(
        s,
        /\/\/ Caution![\s\S]*?signingConfig signingConfigs\.debug/,
        'signingConfig signingConfigs.release',
        "the release build type's debug signingConfig"
      )
    }

    if (!s.includes('NOMAD_VERSION_CODE')) {
      s = replaceOrThrow(
        s,
        /versionCode \d+/,
        "versionCode = Integer.parseInt(System.getenv('NOMAD_VERSION_CODE') ?: '1')",
        'the versionCode line'
      )
      s = replaceOrThrow(
        s,
        /versionName "[^"]*"/,
        "versionName = System.getenv('NOMAD_VERSION_NAME') ?: '1.0.0'",
        'the versionName line'
      )
    }

    cfg.modResults.contents = s
    return cfg
  })
}
