// AUTO-GENERATED by scripts/gen-schema-dts.mjs from
// app/lib/schemas/walled.garden/*.ts — do not edit by hand.
// Registered with monaco.languages.json.jsonDefaults so a .json file whose "type"
// field matches a walled.garden schema gets that schema's autocomplete/validation.

export const WALLED_GARDEN_TYPES = ["walled.garden/person","walled.garden/post","walled.garden/feed","walled.garden/bookmark","walled.garden/comment","walled.garden/follows","walled.garden/reaction","walled.garden/status","walled.garden/vote"];
export const WALLED_GARDEN_JSON_SCHEMA = {
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "walled.garden records & drive manifest",
  "allOf": [
    {
      "if": {
        "required": [
          "type"
        ],
        "properties": {
          "type": {
            "const": "walled.garden/person"
          }
        }
      },
      "then": {
        "$schema": "http://json-schema.org/draft-07/schema#",
        "type": "object",
        "properties": {
          "title": {
            "type": "string",
            "maxLength": 280
          },
          "description": {
            "type": "string",
            "maxLength": 1000
          },
          "type": {
            "type": "string",
            "const": "walled.garden/person"
          },
          "thumb": {
            "type": "string"
          },
          "author": {
            "type": "object",
            "description": "Manifest: information about the drive author",
            "properties": {
              "url": {
                "type": "string",
                "description": "The author profile drive's hyper:// URL"
              }
            }
          },
          "forkOf": {
            "type": "string",
            "description": "Manifest: hyper:// URL this drive was forked from"
          },
          "links": {
            "type": "array",
            "items": {
              "type": "object",
              "properties": {
                "label": {
                  "type": "string",
                  "maxLength": 100
                },
                "href": {
                  "type": "string",
                  "format": "uri"
                }
              },
              "required": [
                "label",
                "href"
              ],
              "additionalProperties": false
            }
          },
          "csp": {
            "type": "string",
            "description": "Manifest: Content-Security-Policy applied to pages served from the drive"
          },
          "ai": {
            "description": "Manifest: opts the drive into nomad.ai — inline config or a pointer hyper:// URL",
            "oneOf": [
              {
                "type": "string",
                "description": "Pointer: delegate to another drive's AI config"
              },
              {
                "type": "object",
                "description": "Inline AI config",
                "properties": {
                  "model": {
                    "type": "string",
                    "description": "Model identifier, e.g. llama3.2:3b"
                  }
                }
              }
            ]
          },
          "chatBubble": {
            "type": "boolean",
            "description": "Manifest: inject a floating AI chat bubble into every page on the drive (requires the ai field)"
          },
          "web_root": {
            "type": "string",
            "description": "Manifest: directory to serve as the web root"
          },
          "fallback_page": {
            "type": "string",
            "description": "Manifest: SPA fallback page path"
          }
        },
        "required": [
          "type",
          "title"
        ],
        "additionalProperties": false
      }
    },
    {
      "if": {
        "required": [
          "type"
        ],
        "properties": {
          "type": {
            "const": "walled.garden/post"
          }
        }
      },
      "then": {
        "$schema": "http://json-schema.org/draft-07/schema#",
        "type": "object",
        "properties": {
          "title": {
            "type": "string",
            "maxLength": 280
          },
          "description": {
            "type": "string",
            "description": "Manifest: short description of the drive's contents"
          },
          "type": {
            "type": "string",
            "const": "walled.garden/post"
          },
          "thumb": {
            "type": "string",
            "description": "Manifest: path within the drive to the thumbnail image"
          },
          "author": {
            "type": "object",
            "properties": {
              "url": {
                "anyOf": [
                  {
                    "type": "string",
                    "format": "uri"
                  },
                  {
                    "type": "null"
                  }
                ]
              },
              "writerKey": {
                "type": "string"
              }
            },
            "additionalProperties": false
          },
          "forkOf": {
            "type": "string",
            "description": "Manifest: hyper:// URL this drive was forked from"
          },
          "links": {
            "type": "object",
            "description": "Manifest: map of named link arrays",
            "additionalProperties": {
              "type": "array",
              "items": {
                "type": "object",
                "properties": {
                  "href": {
                    "type": "string"
                  }
                }
              }
            }
          },
          "csp": {
            "type": "string",
            "description": "Manifest: Content-Security-Policy applied to pages served from the drive"
          },
          "ai": {
            "description": "Manifest: opts the drive into nomad.ai — inline config or a pointer hyper:// URL",
            "oneOf": [
              {
                "type": "string",
                "description": "Pointer: delegate to another drive's AI config"
              },
              {
                "type": "object",
                "description": "Inline AI config",
                "properties": {
                  "model": {
                    "type": "string",
                    "description": "Model identifier, e.g. llama3.2:3b"
                  }
                }
              }
            ]
          },
          "chatBubble": {
            "type": "boolean",
            "description": "Manifest: inject a floating AI chat bubble into every page on the drive (requires the ai field)"
          },
          "web_root": {
            "type": "string",
            "description": "Manifest: directory to serve as the web root"
          },
          "fallback_page": {
            "type": "string",
            "description": "Manifest: SPA fallback page path"
          },
          "summary": {
            "type": "string",
            "maxLength": 560
          },
          "body": {
            "type": "string"
          },
          "category": {
            "type": "string",
            "maxLength": 100
          },
          "tags": {
            "type": "array",
            "items": {
              "type": "string",
              "maxLength": 100,
              "pattern": "^[A-Za-z][A-Za-z0-9\\-_?]*$"
            }
          },
          "draft": {
            "type": "boolean"
          },
          "createdAt": {
            "type": "string",
            "format": "date-time",
            "pattern": "^(?:(?:\\d\\d[2468][048]|\\d\\d[13579][26]|\\d\\d0[48]|[02468][048]00|[13579][26]00)-02-29|\\d{4}-(?:(?:0[13578]|1[02])-(?:0[1-9]|[12]\\d|3[01])|(?:0[469]|11)-(?:0[1-9]|[12]\\d|30)|(?:02)-(?:0[1-9]|1\\d|2[0-8])))T(?:(?:[01]\\d|2[0-3]):[0-5]\\d(?::[0-5]\\d(?:\\.\\d+)?)?(?:Z))$"
          },
          "updatedAt": {
            "type": "string",
            "format": "date-time",
            "pattern": "^(?:(?:\\d\\d[2468][048]|\\d\\d[13579][26]|\\d\\d0[48]|[02468][048]00|[13579][26]00)-02-29|\\d{4}-(?:(?:0[13578]|1[02])-(?:0[1-9]|[12]\\d|3[01])|(?:0[469]|11)-(?:0[1-9]|[12]\\d|30)|(?:02)-(?:0[1-9]|1\\d|2[0-8])))T(?:(?:[01]\\d|2[0-3]):[0-5]\\d(?::[0-5]\\d(?:\\.\\d+)?)?(?:Z))$"
          }
        },
        "required": [
          "type",
          "title",
          "createdAt"
        ],
        "additionalProperties": false
      }
    },
    {
      "if": {
        "required": [
          "type"
        ],
        "properties": {
          "type": {
            "const": "walled.garden/feed"
          }
        }
      },
      "then": {
        "$schema": "http://json-schema.org/draft-07/schema#",
        "type": "object",
        "properties": {
          "title": {
            "type": "string",
            "maxLength": 280
          },
          "description": {
            "type": "string",
            "maxLength": 1000
          },
          "type": {
            "type": "string",
            "const": "walled.garden/feed"
          },
          "thumb": {
            "type": "string",
            "description": "Manifest: path within the drive to the thumbnail image"
          },
          "author": {
            "type": "object",
            "properties": {
              "url": {
                "type": "string",
                "format": "uri"
              }
            },
            "required": [
              "url"
            ],
            "additionalProperties": false
          },
          "forkOf": {
            "type": "string",
            "description": "Manifest: hyper:// URL this drive was forked from"
          },
          "links": {
            "type": "object",
            "description": "Manifest: map of named link arrays",
            "additionalProperties": {
              "type": "array",
              "items": {
                "type": "object",
                "properties": {
                  "href": {
                    "type": "string"
                  }
                }
              }
            }
          },
          "csp": {
            "type": "string",
            "description": "Manifest: Content-Security-Policy applied to pages served from the drive"
          },
          "ai": {
            "description": "Manifest: opts the drive into nomad.ai — inline config or a pointer hyper:// URL",
            "oneOf": [
              {
                "type": "string",
                "description": "Pointer: delegate to another drive's AI config"
              },
              {
                "type": "object",
                "description": "Inline AI config",
                "properties": {
                  "model": {
                    "type": "string",
                    "description": "Model identifier, e.g. llama3.2:3b"
                  }
                }
              }
            ]
          },
          "chatBubble": {
            "type": "boolean",
            "description": "Manifest: inject a floating AI chat bubble into every page on the drive (requires the ai field)"
          },
          "web_root": {
            "type": "string",
            "description": "Manifest: directory to serve as the web root"
          },
          "fallback_page": {
            "type": "string",
            "description": "Manifest: SPA fallback page path"
          },
          "itemsPath": {
            "type": "string",
            "maxLength": 280
          },
          "itemType": {
            "type": "string",
            "maxLength": 100
          },
          "language": {
            "type": "string",
            "maxLength": 20
          },
          "icon": {
            "type": "string"
          }
        },
        "required": [
          "type",
          "title"
        ],
        "additionalProperties": false
      }
    },
    {
      "if": {
        "required": [
          "type"
        ],
        "properties": {
          "type": {
            "const": "walled.garden/bookmark"
          }
        }
      },
      "then": {
        "$schema": "http://json-schema.org/draft-07/schema#",
        "type": "object",
        "properties": {
          "title": {
            "type": "string",
            "maxLength": 280
          },
          "description": {
            "type": "string",
            "maxLength": 560
          },
          "type": {
            "type": "string",
            "const": "walled.garden/bookmark"
          },
          "thumb": {
            "type": "string",
            "description": "Manifest: path within the drive to the thumbnail image"
          },
          "author": {
            "type": "object",
            "description": "Manifest: information about the drive author",
            "properties": {
              "url": {
                "type": "string",
                "description": "The author profile drive's hyper:// URL"
              }
            }
          },
          "forkOf": {
            "type": "string",
            "description": "Manifest: hyper:// URL this drive was forked from"
          },
          "links": {
            "type": "object",
            "description": "Manifest: map of named link arrays",
            "additionalProperties": {
              "type": "array",
              "items": {
                "type": "object",
                "properties": {
                  "href": {
                    "type": "string"
                  }
                }
              }
            }
          },
          "csp": {
            "type": "string",
            "description": "Manifest: Content-Security-Policy applied to pages served from the drive"
          },
          "ai": {
            "description": "Manifest: opts the drive into nomad.ai — inline config or a pointer hyper:// URL",
            "oneOf": [
              {
                "type": "string",
                "description": "Pointer: delegate to another drive's AI config"
              },
              {
                "type": "object",
                "description": "Inline AI config",
                "properties": {
                  "model": {
                    "type": "string",
                    "description": "Model identifier, e.g. llama3.2:3b"
                  }
                }
              }
            ]
          },
          "chatBubble": {
            "type": "boolean",
            "description": "Manifest: inject a floating AI chat bubble into every page on the drive (requires the ai field)"
          },
          "web_root": {
            "type": "string",
            "description": "Manifest: directory to serve as the web root"
          },
          "fallback_page": {
            "type": "string",
            "description": "Manifest: SPA fallback page path"
          },
          "href": {
            "type": "string",
            "maxLength": 10000,
            "format": "uri"
          },
          "tags": {
            "type": "array",
            "items": {
              "type": "string",
              "maxLength": 100,
              "pattern": "^[A-Za-z][A-Za-z0-9\\-_?]*$"
            }
          },
          "createdAt": {
            "type": "string",
            "format": "date-time",
            "pattern": "^(?:(?:\\d\\d[2468][048]|\\d\\d[13579][26]|\\d\\d0[48]|[02468][048]00|[13579][26]00)-02-29|\\d{4}-(?:(?:0[13578]|1[02])-(?:0[1-9]|[12]\\d|3[01])|(?:0[469]|11)-(?:0[1-9]|[12]\\d|30)|(?:02)-(?:0[1-9]|1\\d|2[0-8])))T(?:(?:[01]\\d|2[0-3]):[0-5]\\d(?::[0-5]\\d(?:\\.\\d+)?)?(?:Z))$"
          },
          "updatedAt": {
            "type": "string",
            "format": "date-time",
            "pattern": "^(?:(?:\\d\\d[2468][048]|\\d\\d[13579][26]|\\d\\d0[48]|[02468][048]00|[13579][26]00)-02-29|\\d{4}-(?:(?:0[13578]|1[02])-(?:0[1-9]|[12]\\d|3[01])|(?:0[469]|11)-(?:0[1-9]|[12]\\d|30)|(?:02)-(?:0[1-9]|1\\d|2[0-8])))T(?:(?:[01]\\d|2[0-3]):[0-5]\\d(?::[0-5]\\d(?:\\.\\d+)?)?(?:Z))$"
          }
        },
        "required": [
          "type",
          "href",
          "title",
          "createdAt"
        ],
        "additionalProperties": false
      }
    },
    {
      "if": {
        "required": [
          "type"
        ],
        "properties": {
          "type": {
            "const": "walled.garden/comment"
          }
        }
      },
      "then": {
        "$schema": "http://json-schema.org/draft-07/schema#",
        "type": "object",
        "properties": {
          "title": {
            "type": "string",
            "description": "Manifest: human-readable name for the drive"
          },
          "description": {
            "type": "string",
            "description": "Manifest: short description of the drive's contents"
          },
          "type": {
            "type": "string",
            "const": "walled.garden/comment"
          },
          "thumb": {
            "type": "string",
            "description": "Manifest: path within the drive to the thumbnail image"
          },
          "author": {
            "type": "object",
            "description": "Manifest: information about the drive author",
            "properties": {
              "url": {
                "type": "string",
                "description": "The author profile drive's hyper:// URL"
              }
            }
          },
          "forkOf": {
            "type": "string",
            "description": "Manifest: hyper:// URL this drive was forked from"
          },
          "links": {
            "type": "object",
            "description": "Manifest: map of named link arrays",
            "additionalProperties": {
              "type": "array",
              "items": {
                "type": "object",
                "properties": {
                  "href": {
                    "type": "string"
                  }
                }
              }
            }
          },
          "csp": {
            "type": "string",
            "description": "Manifest: Content-Security-Policy applied to pages served from the drive"
          },
          "ai": {
            "description": "Manifest: opts the drive into nomad.ai — inline config or a pointer hyper:// URL",
            "oneOf": [
              {
                "type": "string",
                "description": "Pointer: delegate to another drive's AI config"
              },
              {
                "type": "object",
                "description": "Inline AI config",
                "properties": {
                  "model": {
                    "type": "string",
                    "description": "Model identifier, e.g. llama3.2:3b"
                  }
                }
              }
            ]
          },
          "chatBubble": {
            "type": "boolean",
            "description": "Manifest: inject a floating AI chat bubble into every page on the drive (requires the ai field)"
          },
          "web_root": {
            "type": "string",
            "description": "Manifest: directory to serve as the web root"
          },
          "fallback_page": {
            "type": "string",
            "description": "Manifest: SPA fallback page path"
          },
          "topic": {
            "type": "string",
            "format": "uri"
          },
          "replyTo": {
            "type": "string",
            "format": "uri"
          },
          "body": {
            "type": "string"
          },
          "createdAt": {
            "type": "string",
            "format": "date-time",
            "pattern": "^(?:(?:\\d\\d[2468][048]|\\d\\d[13579][26]|\\d\\d0[48]|[02468][048]00|[13579][26]00)-02-29|\\d{4}-(?:(?:0[13578]|1[02])-(?:0[1-9]|[12]\\d|3[01])|(?:0[469]|11)-(?:0[1-9]|[12]\\d|30)|(?:02)-(?:0[1-9]|1\\d|2[0-8])))T(?:(?:[01]\\d|2[0-3]):[0-5]\\d(?::[0-5]\\d(?:\\.\\d+)?)?(?:Z))$"
          },
          "updatedAt": {
            "type": "string",
            "format": "date-time",
            "pattern": "^(?:(?:\\d\\d[2468][048]|\\d\\d[13579][26]|\\d\\d0[48]|[02468][048]00|[13579][26]00)-02-29|\\d{4}-(?:(?:0[13578]|1[02])-(?:0[1-9]|[12]\\d|3[01])|(?:0[469]|11)-(?:0[1-9]|[12]\\d|30)|(?:02)-(?:0[1-9]|1\\d|2[0-8])))T(?:(?:[01]\\d|2[0-3]):[0-5]\\d(?::[0-5]\\d(?:\\.\\d+)?)?(?:Z))$"
          }
        },
        "required": [
          "type",
          "topic",
          "body",
          "createdAt"
        ],
        "additionalProperties": false
      }
    },
    {
      "if": {
        "required": [
          "type"
        ],
        "properties": {
          "type": {
            "const": "walled.garden/follows"
          }
        }
      },
      "then": {
        "$schema": "http://json-schema.org/draft-07/schema#",
        "type": "object",
        "properties": {
          "title": {
            "type": "string",
            "description": "Manifest: human-readable name for the drive"
          },
          "description": {
            "type": "string",
            "description": "Manifest: short description of the drive's contents"
          },
          "type": {
            "type": "string",
            "const": "walled.garden/follows"
          },
          "thumb": {
            "type": "string",
            "description": "Manifest: path within the drive to the thumbnail image"
          },
          "author": {
            "type": "object",
            "description": "Manifest: information about the drive author",
            "properties": {
              "url": {
                "type": "string",
                "description": "The author profile drive's hyper:// URL"
              }
            }
          },
          "forkOf": {
            "type": "string",
            "description": "Manifest: hyper:// URL this drive was forked from"
          },
          "links": {
            "type": "object",
            "description": "Manifest: map of named link arrays",
            "additionalProperties": {
              "type": "array",
              "items": {
                "type": "object",
                "properties": {
                  "href": {
                    "type": "string"
                  }
                }
              }
            }
          },
          "csp": {
            "type": "string",
            "description": "Manifest: Content-Security-Policy applied to pages served from the drive"
          },
          "ai": {
            "description": "Manifest: opts the drive into nomad.ai — inline config or a pointer hyper:// URL",
            "oneOf": [
              {
                "type": "string",
                "description": "Pointer: delegate to another drive's AI config"
              },
              {
                "type": "object",
                "description": "Inline AI config",
                "properties": {
                  "model": {
                    "type": "string",
                    "description": "Model identifier, e.g. llama3.2:3b"
                  }
                }
              }
            ]
          },
          "chatBubble": {
            "type": "boolean",
            "description": "Manifest: inject a floating AI chat bubble into every page on the drive (requires the ai field)"
          },
          "web_root": {
            "type": "string",
            "description": "Manifest: directory to serve as the web root"
          },
          "fallback_page": {
            "type": "string",
            "description": "Manifest: SPA fallback page path"
          },
          "urls": {
            "type": "array",
            "items": {
              "type": "string",
              "format": "uri"
            }
          }
        },
        "required": [
          "type",
          "urls"
        ],
        "additionalProperties": false
      }
    },
    {
      "if": {
        "required": [
          "type"
        ],
        "properties": {
          "type": {
            "const": "walled.garden/reaction"
          }
        }
      },
      "then": {
        "$schema": "http://json-schema.org/draft-07/schema#",
        "type": "object",
        "properties": {
          "title": {
            "type": "string",
            "description": "Manifest: human-readable name for the drive"
          },
          "description": {
            "type": "string",
            "description": "Manifest: short description of the drive's contents"
          },
          "type": {
            "type": "string",
            "const": "walled.garden/reaction"
          },
          "thumb": {
            "type": "string",
            "description": "Manifest: path within the drive to the thumbnail image"
          },
          "author": {
            "type": "object",
            "description": "Manifest: information about the drive author",
            "properties": {
              "url": {
                "type": "string",
                "description": "The author profile drive's hyper:// URL"
              }
            }
          },
          "forkOf": {
            "type": "string",
            "description": "Manifest: hyper:// URL this drive was forked from"
          },
          "links": {
            "type": "object",
            "description": "Manifest: map of named link arrays",
            "additionalProperties": {
              "type": "array",
              "items": {
                "type": "object",
                "properties": {
                  "href": {
                    "type": "string"
                  }
                }
              }
            }
          },
          "csp": {
            "type": "string",
            "description": "Manifest: Content-Security-Policy applied to pages served from the drive"
          },
          "ai": {
            "description": "Manifest: opts the drive into nomad.ai — inline config or a pointer hyper:// URL",
            "oneOf": [
              {
                "type": "string",
                "description": "Pointer: delegate to another drive's AI config"
              },
              {
                "type": "object",
                "description": "Inline AI config",
                "properties": {
                  "model": {
                    "type": "string",
                    "description": "Model identifier, e.g. llama3.2:3b"
                  }
                }
              }
            ]
          },
          "chatBubble": {
            "type": "boolean",
            "description": "Manifest: inject a floating AI chat bubble into every page on the drive (requires the ai field)"
          },
          "web_root": {
            "type": "string",
            "description": "Manifest: directory to serve as the web root"
          },
          "fallback_page": {
            "type": "string",
            "description": "Manifest: SPA fallback page path"
          },
          "topic": {
            "type": "string",
            "format": "uri"
          },
          "phrases": {
            "type": "array",
            "items": {
              "type": "string",
              "maxLength": 20,
              "pattern": "^[a-z ]+$"
            }
          }
        },
        "required": [
          "type",
          "topic",
          "phrases"
        ],
        "additionalProperties": false
      }
    },
    {
      "if": {
        "required": [
          "type"
        ],
        "properties": {
          "type": {
            "const": "walled.garden/status"
          }
        }
      },
      "then": {
        "$schema": "http://json-schema.org/draft-07/schema#",
        "type": "object",
        "properties": {
          "title": {
            "type": "string",
            "description": "Manifest: human-readable name for the drive"
          },
          "description": {
            "type": "string",
            "description": "Manifest: short description of the drive's contents"
          },
          "type": {
            "type": "string",
            "const": "walled.garden/status"
          },
          "thumb": {
            "type": "string",
            "description": "Manifest: path within the drive to the thumbnail image"
          },
          "author": {
            "type": "object",
            "description": "Manifest: information about the drive author",
            "properties": {
              "url": {
                "type": "string",
                "description": "The author profile drive's hyper:// URL"
              }
            }
          },
          "forkOf": {
            "type": "string",
            "description": "Manifest: hyper:// URL this drive was forked from"
          },
          "links": {
            "type": "object",
            "description": "Manifest: map of named link arrays",
            "additionalProperties": {
              "type": "array",
              "items": {
                "type": "object",
                "properties": {
                  "href": {
                    "type": "string"
                  }
                }
              }
            }
          },
          "csp": {
            "type": "string",
            "description": "Manifest: Content-Security-Policy applied to pages served from the drive"
          },
          "ai": {
            "description": "Manifest: opts the drive into nomad.ai — inline config or a pointer hyper:// URL",
            "oneOf": [
              {
                "type": "string",
                "description": "Pointer: delegate to another drive's AI config"
              },
              {
                "type": "object",
                "description": "Inline AI config",
                "properties": {
                  "model": {
                    "type": "string",
                    "description": "Model identifier, e.g. llama3.2:3b"
                  }
                }
              }
            ]
          },
          "chatBubble": {
            "type": "boolean",
            "description": "Manifest: inject a floating AI chat bubble into every page on the drive (requires the ai field)"
          },
          "web_root": {
            "type": "string",
            "description": "Manifest: directory to serve as the web root"
          },
          "fallback_page": {
            "type": "string",
            "description": "Manifest: SPA fallback page path"
          },
          "body": {
            "type": "string",
            "maxLength": 1000000
          },
          "createdAt": {
            "type": "string",
            "format": "date-time",
            "pattern": "^(?:(?:\\d\\d[2468][048]|\\d\\d[13579][26]|\\d\\d0[48]|[02468][048]00|[13579][26]00)-02-29|\\d{4}-(?:(?:0[13578]|1[02])-(?:0[1-9]|[12]\\d|3[01])|(?:0[469]|11)-(?:0[1-9]|[12]\\d|30)|(?:02)-(?:0[1-9]|1\\d|2[0-8])))T(?:(?:[01]\\d|2[0-3]):[0-5]\\d(?::[0-5]\\d(?:\\.\\d+)?)?(?:Z))$"
          },
          "updatedAt": {
            "type": "string",
            "format": "date-time",
            "pattern": "^(?:(?:\\d\\d[2468][048]|\\d\\d[13579][26]|\\d\\d0[48]|[02468][048]00|[13579][26]00)-02-29|\\d{4}-(?:(?:0[13578]|1[02])-(?:0[1-9]|[12]\\d|3[01])|(?:0[469]|11)-(?:0[1-9]|[12]\\d|30)|(?:02)-(?:0[1-9]|1\\d|2[0-8])))T(?:(?:[01]\\d|2[0-3]):[0-5]\\d(?::[0-5]\\d(?:\\.\\d+)?)?(?:Z))$"
          }
        },
        "required": [
          "type",
          "body",
          "createdAt"
        ],
        "additionalProperties": false
      }
    },
    {
      "if": {
        "required": [
          "type"
        ],
        "properties": {
          "type": {
            "const": "walled.garden/vote"
          }
        }
      },
      "then": {
        "$schema": "http://json-schema.org/draft-07/schema#",
        "type": "object",
        "properties": {
          "title": {
            "type": "string",
            "description": "Manifest: human-readable name for the drive"
          },
          "description": {
            "type": "string",
            "description": "Manifest: short description of the drive's contents"
          },
          "type": {
            "type": "string",
            "const": "walled.garden/vote"
          },
          "thumb": {
            "type": "string",
            "description": "Manifest: path within the drive to the thumbnail image"
          },
          "author": {
            "type": "object",
            "description": "Manifest: information about the drive author",
            "properties": {
              "url": {
                "type": "string",
                "description": "The author profile drive's hyper:// URL"
              }
            }
          },
          "forkOf": {
            "type": "string",
            "description": "Manifest: hyper:// URL this drive was forked from"
          },
          "links": {
            "type": "object",
            "description": "Manifest: map of named link arrays",
            "additionalProperties": {
              "type": "array",
              "items": {
                "type": "object",
                "properties": {
                  "href": {
                    "type": "string"
                  }
                }
              }
            }
          },
          "csp": {
            "type": "string",
            "description": "Manifest: Content-Security-Policy applied to pages served from the drive"
          },
          "ai": {
            "description": "Manifest: opts the drive into nomad.ai — inline config or a pointer hyper:// URL",
            "oneOf": [
              {
                "type": "string",
                "description": "Pointer: delegate to another drive's AI config"
              },
              {
                "type": "object",
                "description": "Inline AI config",
                "properties": {
                  "model": {
                    "type": "string",
                    "description": "Model identifier, e.g. llama3.2:3b"
                  }
                }
              }
            ]
          },
          "chatBubble": {
            "type": "boolean",
            "description": "Manifest: inject a floating AI chat bubble into every page on the drive (requires the ai field)"
          },
          "web_root": {
            "type": "string",
            "description": "Manifest: directory to serve as the web root"
          },
          "fallback_page": {
            "type": "string",
            "description": "Manifest: SPA fallback page path"
          },
          "topic": {
            "type": "string",
            "format": "uri"
          },
          "vote": {
            "anyOf": [
              {
                "type": "number",
                "const": -1
              },
              {
                "type": "number",
                "const": 1
              }
            ]
          },
          "createdAt": {
            "type": "string",
            "format": "date-time",
            "pattern": "^(?:(?:\\d\\d[2468][048]|\\d\\d[13579][26]|\\d\\d0[48]|[02468][048]00|[13579][26]00)-02-29|\\d{4}-(?:(?:0[13578]|1[02])-(?:0[1-9]|[12]\\d|3[01])|(?:0[469]|11)-(?:0[1-9]|[12]\\d|30)|(?:02)-(?:0[1-9]|1\\d|2[0-8])))T(?:(?:[01]\\d|2[0-3]):[0-5]\\d(?::[0-5]\\d(?:\\.\\d+)?)?(?:Z))$"
          },
          "updatedAt": {
            "type": "string",
            "format": "date-time",
            "pattern": "^(?:(?:\\d\\d[2468][048]|\\d\\d[13579][26]|\\d\\d0[48]|[02468][048]00|[13579][26]00)-02-29|\\d{4}-(?:(?:0[13578]|1[02])-(?:0[1-9]|[12]\\d|3[01])|(?:0[469]|11)-(?:0[1-9]|[12]\\d|30)|(?:02)-(?:0[1-9]|1\\d|2[0-8])))T(?:(?:[01]\\d|2[0-3]):[0-5]\\d(?::[0-5]\\d(?:\\.\\d+)?)?(?:Z))$"
          }
        },
        "required": [
          "type",
          "topic",
          "vote",
          "createdAt"
        ],
        "additionalProperties": false
      }
    },
    {
      "if": {
        "not": {
          "required": [
            "type"
          ],
          "properties": {
            "type": {
              "enum": [
                "walled.garden/person",
                "walled.garden/post",
                "walled.garden/feed",
                "walled.garden/bookmark",
                "walled.garden/comment",
                "walled.garden/follows",
                "walled.garden/reaction",
                "walled.garden/status",
                "walled.garden/vote"
              ]
            }
          }
        }
      },
      "then": {
        "type": "object",
        "properties": {
          "title": {
            "type": "string",
            "description": "Manifest: human-readable name for the drive"
          },
          "description": {
            "type": "string",
            "description": "Manifest: short description of the drive's contents"
          },
          "type": {
            "type": "string",
            "description": "Manifest: type identifier (e.g. unwalled.garden/website)"
          },
          "thumb": {
            "type": "string",
            "description": "Manifest: path within the drive to the thumbnail image"
          },
          "author": {
            "type": "object",
            "description": "Manifest: information about the drive author",
            "properties": {
              "url": {
                "type": "string",
                "description": "The author profile drive's hyper:// URL"
              }
            }
          },
          "forkOf": {
            "type": "string",
            "description": "Manifest: hyper:// URL this drive was forked from"
          },
          "links": {
            "type": "object",
            "description": "Manifest: map of named link arrays",
            "additionalProperties": {
              "type": "array",
              "items": {
                "type": "object",
                "properties": {
                  "href": {
                    "type": "string"
                  }
                }
              }
            }
          },
          "csp": {
            "type": "string",
            "description": "Manifest: Content-Security-Policy applied to pages served from the drive"
          },
          "ai": {
            "description": "Manifest: opts the drive into nomad.ai — inline config or a pointer hyper:// URL",
            "oneOf": [
              {
                "type": "string",
                "description": "Pointer: delegate to another drive's AI config"
              },
              {
                "type": "object",
                "description": "Inline AI config",
                "properties": {
                  "model": {
                    "type": "string",
                    "description": "Model identifier, e.g. llama3.2:3b"
                  }
                }
              }
            ]
          },
          "chatBubble": {
            "type": "boolean",
            "description": "Manifest: inject a floating AI chat bubble into every page on the drive (requires the ai field)"
          },
          "web_root": {
            "type": "string",
            "description": "Manifest: directory to serve as the web root"
          },
          "fallback_page": {
            "type": "string",
            "description": "Manifest: SPA fallback page path"
          }
        }
      }
    }
  ]
};
